"use client";

import { useState, useEffect, use, useCallback } from "react";
import { useRouter } from "@/i18n/routing";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Separator } from "@/components/ui/separator";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { motion } from "framer-motion";
import {
  ArrowLeft,
  Loader2,
  Plus,
  Code2,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Eye,
  Pencil,
  Trash2,
  Shield,
  FileJson,
  Sparkles,
  ExternalLink,
} from "lucide-react";
import { toast } from "sonner";

interface StructuredDataEntry {
  id: string;
  pageId: string | null;
  url: string | null;
  type: string;
  data: string;
  isValid: boolean;
  validationErrors: string | null;
  missingFields: string | null;
  isAutoGenerated: boolean;
  approvedBy: string | null;
  approvedAt: string | null;
  createdAt: string;
  updatedAt: string;
  validation?: {
    isValid: boolean;
    errors: string[];
    missingFields: string[];
    warnings: string[];
  };
  page?: {
    id: string;
    url: string;
    title: string | null;
  } | null;
}

interface CrawledPage {
  id: string;
  url: string;
  title: string | null;
}

const typeLabels: Record<string, string> = {
  ORGANIZATION: "Organisatie",
  LOCAL_BUSINESS: "Lokale onderneming",
  PRODUCT: "Product",
  OFFER: "Aanbod",
  REVIEW: "Beoordeling",
  BREADCRUMB_LIST: "Broodkruimel",
  ARTICLE: "Artikel",
  FAQ_PAGE: "FAQ-pagina",
  HOW_TO: "Instructie",
  PERSON: "Persoon",
  EVENT: "Evenement",
  JOB_POSTING: "Vacature",
  SERVICE: "Dienst",
  WEB_SITE: "Website",
  WEB_PAGE: "Webpagina",
};

const typeColors: Record<string, string> = {
  ORGANIZATION:
    "bg-violet-100 text-violet-800 border-violet-200 dark:bg-violet-900/30 dark:text-violet-400 dark:border-violet-800",
  LOCAL_BUSINESS:
    "bg-orange-100 text-orange-800 border-orange-200 dark:bg-orange-900/30 dark:text-orange-400 dark:border-orange-800",
  PRODUCT:
    "bg-emerald-100 text-emerald-800 border-emerald-200 dark:bg-emerald-900/30 dark:text-emerald-400 dark:border-emerald-800",
  OFFER: "bg-cyan-100 text-cyan-800 border-cyan-200 dark:bg-cyan-900/30 dark:text-cyan-400 dark:border-cyan-800",
  REVIEW:
    "bg-yellow-100 text-yellow-800 border-yellow-200 dark:bg-yellow-900/30 dark:text-yellow-400 dark:border-yellow-800",
  BREADCRUMB_LIST:
    "bg-pink-100 text-pink-800 border-pink-200 dark:bg-pink-900/30 dark:text-pink-400 dark:border-pink-800",
  ARTICLE:
    "bg-blue-100 text-blue-800 border-blue-200 dark:bg-blue-900/30 dark:text-blue-400 dark:border-blue-800",
  FAQ_PAGE:
    "bg-teal-100 text-teal-800 border-teal-200 dark:bg-teal-900/30 dark:text-teal-400 dark:border-teal-800",
  HOW_TO: "bg-indigo-100 text-indigo-800 border-indigo-200 dark:bg-indigo-900/30 dark:text-indigo-400 dark:border-indigo-800",
  PERSON:
    "bg-rose-100 text-rose-800 border-rose-200 dark:bg-rose-900/30 dark:text-rose-400 dark:border-rose-800",
  EVENT: "bg-amber-100 text-amber-800 border-amber-200 dark:bg-amber-900/30 dark:text-amber-400 dark:border-amber-800",
  JOB_POSTING:
    "bg-fuchsia-100 text-fuchsia-800 border-fuchsia-200 dark:bg-fuchsia-900/30 dark:text-fuchsia-400 dark:border-fuchsia-800",
  SERVICE:
    "bg-lime-100 text-lime-800 border-lime-200 dark:bg-lime-900/30 dark:text-lime-400 dark:border-lime-800",
  WEB_SITE:
    "bg-sky-100 text-sky-800 border-sky-200 dark:bg-sky-900/30 dark:text-sky-400 dark:border-sky-800",
  WEB_PAGE:
    "bg-slate-100 text-slate-800 border-slate-200 dark:bg-slate-900/30 dark:text-slate-400 dark:border-slate-800",
};

export default function StructuredDataPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id: projectId } = use(params);
  const router = useRouter();

  const [entries, setEntries] = useState<StructuredDataEntry[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [typeFilter, setTypeFilter] = useState("all");

  // Generate dialog
  const [showGenerateDialog, setShowGenerateDialog] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generateForm, setGenerateForm] = useState({
    type: "ORGANIZATION",
    pageId: "",
    url: "",
  });

  // Preview dialog
  const [showPreviewDialog, setShowPreviewDialog] = useState(false);
  const [previewEntry, setPreviewEntry] = useState<StructuredDataEntry | null>(null);

  // Edit dialog
  const [showEditDialog, setShowEditDialog] = useState(false);
  const [editEntry, setEditEntry] = useState<StructuredDataEntry | null>(null);
  const [editData, setEditData] = useState("");
  const [isSaving, setIsSaving] = useState(false);

  // Detail dialog
  const [showDetailDialog, setShowDetailDialog] = useState(false);
  const [detailEntry, setDetailEntry] = useState<StructuredDataEntry | null>(null);
  const [isLoadingDetail, setIsLoadingDetail] = useState(false);

  // Delete dialog
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);
  const [deleteEntry, setDeleteEntry] = useState<StructuredDataEntry | null>(null);

  // Approve action
  const [approvingId, setApprovingId] = useState<string | null>(null);
  const [validatingId, setValidatingId] = useState<string | null>(null);

  // Crawled pages for selector
  const [crawledPages, setCrawledPages] = useState<CrawledPage[]>([]);
  const [useUrlInput, setUseUrlInput] = useState(false);

  const fetchEntries = useCallback(async () => {
    setIsLoading(true);
    try {
      const params = new URLSearchParams();
      if (typeFilter !== "all") params.set("type", typeFilter);

      const res = await fetch(
        `/api/projects/${projectId}/structured-data?${params.toString()}`
      );
      if (res.ok) {
        const data = await res.json();
        setEntries(data.data || []);
      }
    } catch {
      toast.error("Fout bij ophalen gestructureerde data");
    } finally {
      setIsLoading(false);
    }
  }, [projectId, typeFilter]);

  const fetchCrawledPages = useCallback(async () => {
    try {
      const res = await fetch(
        `/api/projects/${projectId}/pages?pageSize=100`
      );
      if (res.ok) {
        const data = await res.json();
        setCrawledPages(data.data?.pages || data.data || []);
      }
    } catch {
      // silently fail
    }
  }, [projectId]);

  useEffect(() => {
    fetchEntries();
  }, [fetchEntries]);

  useEffect(() => {
    if (showGenerateDialog) {
      fetchCrawledPages();
    }
  }, [showGenerateDialog, fetchCrawledPages]);

  async function handleGenerate() {
    if (!generateForm.type) {
      toast.error("Selecteer een type gestructureerde data");
      return;
    }
    setIsGenerating(true);
    try {
      const body: Record<string, unknown> = {
        type: generateForm.type,
      };
      if (generateForm.pageId) {
        body.pageId = generateForm.pageId;
      } else if (generateForm.url) {
        body.url = generateForm.url;
      }

      const res = await fetch(`/api/projects/${projectId}/structured-data`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });

      if (res.ok) {
        toast.success("Gestructureerde data gegenereerd");
        setShowGenerateDialog(false);
        setGenerateForm({ type: "ORGANIZATION", pageId: "", url: "" });
        fetchEntries();
      } else {
        const data = await res.json();
        toast.error(data.error || "Fout bij genereren gestructureerde data");
      }
    } catch {
      toast.error("Fout bij genereren gestructureerde data");
    } finally {
      setIsGenerating(false);
    }
  }

  async function handleViewDetail(entry: StructuredDataEntry) {
    setIsLoadingDetail(true);
    setShowDetailDialog(true);
    try {
      const res = await fetch(
        `/api/projects/${projectId}/structured-data/${entry.id}`
      );
      if (res.ok) {
        const data = await res.json();
        setDetailEntry(data.data || entry);
      } else {
        setDetailEntry(entry);
      }
    } catch {
      setDetailEntry(entry);
    } finally {
      setIsLoadingDetail(false);
    }
  }

  function handlePreview(entry: StructuredDataEntry) {
    setPreviewEntry(entry);
    setShowPreviewDialog(true);
  }

  function handleEdit(entry: StructuredDataEntry) {
    setEditEntry(entry);
    setEditData(entry.data);
    setShowEditDialog(true);
  }

  async function handleSaveEdit() {
    if (!editEntry) return;
    setIsSaving(true);
    try {
      // Validate JSON
      try {
        JSON.parse(editData);
      } catch {
        toast.error("Ongeldige JSON-syntax");
        setIsSaving(false);
        return;
      }

      const res = await fetch(
        `/api/projects/${projectId}/structured-data/${editEntry.id}`,
        {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ data: editData }),
        }
      );

      if (res.ok) {
        toast.success("Gestructureerde data bijgewerkt");
        setShowEditDialog(false);
        setEditEntry(null);
        fetchEntries();
      } else {
        const data = await res.json();
        toast.error(data.error || "Fout bij bijwerken");
      }
    } catch {
      toast.error("Fout bij bijwerken");
    } finally {
      setIsSaving(false);
    }
  }

  async function handleApprove(entry: StructuredDataEntry) {
    setApprovingId(entry.id);
    try {
      const res = await fetch(
        `/api/projects/${projectId}/structured-data/${entry.id}`,
        {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ approve: true }),
        }
      );
      if (res.ok) {
        toast.success("Gestructureerde data goedgekeurd");
        fetchEntries();
      } else {
        const data = await res.json();
        toast.error(data.error || "Fout bij goedkeuren");
      }
    } catch {
      toast.error("Fout bij goedkeuren");
    } finally {
      setApprovingId(null);
    }
  }

  async function handleValidate(entry: StructuredDataEntry) {
    setValidatingId(entry.id);
    try {
      const res = await fetch(
        `/api/projects/${projectId}/structured-data/${entry.id}`
      );
      if (res.ok) {
        const data = await res.json();
        toast.success(
          data.data?.validation?.isValid
            ? "Validatie geslaagd: geen fouten gevonden"
            : "Validatie voltooid: fouten gevonden"
        );
        fetchEntries();
      } else {
        toast.error("Fout bij valideren");
      }
    } catch {
      toast.error("Fout bij valideren");
    } finally {
      setValidatingId(null);
    }
  }

  async function handleDelete() {
    if (!deleteEntry) return;
    try {
      const res = await fetch(
        `/api/projects/${projectId}/structured-data/${deleteEntry.id}`,
        { method: "DELETE" }
      );
      if (res.ok) {
        toast.success("Gestructureerde data verwijderd");
        setShowDeleteDialog(false);
        setDeleteEntry(null);
        fetchEntries();
      } else {
        toast.error("Fout bij verwijderen");
      }
    } catch {
      toast.error("Fout bij verwijderen");
    }
  }

  function parseJsonArray(json: string | null | undefined): string[] {
    if (!json) return [];
    try {
      const parsed = JSON.parse(json);
      return Array.isArray(parsed) ? parsed : [];
    } catch {
      return [];
    }
  }

  function formatJsonLd(data: string): string {
    try {
      return JSON.stringify(JSON.parse(data), null, 2);
    } catch {
      return data;
    }
  }

  function syntaxHighlight(json: string): React.ReactNode {
    const formatted = formatJsonLd(json);
    // Simple syntax highlighting for JSON
    const parts = formatted.split(/("(?:[^"\\]|\\.)*")\s*:/g);
    return parts.map((part, i) => {
      // Keys (odd indices after split by pattern)
      if (i % 2 === 1) {
        return (
          <span key={i} className="text-emerald-600 dark:text-emerald-400">
            {part}:
          </span>
        );
      }
      // Values - highlight strings, numbers, booleans
      return part.split(/("(?:[^"\\]|\\.)*")|(\b(?:true|false|null)\b)|(\b\d+\.?\d*\b)/g).map((segment, j) => {
        if (!segment) return null;
        if (segment.startsWith('"') && segment.endsWith('"')) {
          return (
            <span key={`${i}-${j}`} className="text-amber-600 dark:text-amber-400">
              {segment}
            </span>
          );
        }
        if (segment === "true" || segment === "false") {
          return (
            <span key={`${i}-${j}`} className="text-blue-600 dark:text-blue-400">
              {segment}
            </span>
          );
        }
        if (segment === "null") {
          return (
            <span key={`${i}-${j}`} className="text-red-500">
              {segment}
            </span>
          );
        }
        if (/^\d+\.?\d*$/.test(segment)) {
          return (
            <span key={`${i}-${j}`} className="text-violet-600 dark:text-violet-400">
              {segment}
            </span>
          );
        }
        return <span key={`${i}-${j}`}>{segment}</span>;
      });
    });
  }

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-[calc(100vh-3.5rem)]">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="p-4 md:p-6 space-y-6"
    >
      {/* Header */}
      <div className="flex items-center gap-4">
        <Button
          variant="ghost"
          size="icon"
          onClick={() => router.push(`/projects/${projectId}`)}
        >
          <ArrowLeft className="h-4 w-4" />
        </Button>
        <div className="flex-1">
          <h1 className="text-2xl font-bold tracking-tight">
            Gestructureerde data
          </h1>
          <p className="text-muted-foreground text-sm">
            Genereer en beheer JSON-LD gestructureerde data
          </p>
        </div>
        <Button onClick={() => setShowGenerateDialog(true)}>
          <Sparkles className="mr-2 h-4 w-4" />
          Genereer gestructureerde data
        </Button>
      </div>

      {/* Filters */}
      <Card>
        <CardContent className="p-4">
          <div className="flex flex-col sm:flex-row gap-4">
            <Select
              value={typeFilter}
              onValueChange={setTypeFilter}
            >
              <SelectTrigger className="w-full sm:w-[250px]">
                <SelectValue placeholder="Filter op type" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">Alle types</SelectItem>
                {Object.entries(typeLabels).map(([key, label]) => (
                  <SelectItem key={key} value={key}>
                    {label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      {/* Entries Table */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base flex items-center gap-2">
            <FileJson className="h-4 w-4" />
            Gestructureerde data ({entries.length})
          </CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          {entries.length === 0 ? (
            <div className="p-8 text-center text-muted-foreground">
              <FileJson className="h-12 w-12 mx-auto mb-3 opacity-50" />
              <p className="font-medium">
                Geen gestructureerde data gevonden
              </p>
              <p className="text-sm mt-1">
                Genereer je eerste gestructureerde data om te beginnen
              </p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Type</TableHead>
                    <TableHead>Pagina / URL</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Geautoriseerd</TableHead>
                    <TableHead>Aangemaakt</TableHead>
                    <TableHead className="text-right">Acties</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {entries.map((entry) => {
                    const validationErrors = parseJsonArray(entry.validationErrors);
                    const missingFields = parseJsonArray(entry.missingFields);
                    const displayUrl = entry.url || entry.page?.url || "—";
                    const pageTitle = entry.page?.title;

                    return (
                      <TableRow
                        key={entry.id}
                        className="cursor-pointer hover:bg-muted/50"
                        onClick={() => handleViewDetail(entry)}
                      >
                        <TableCell>
                          <Badge
                            variant="outline"
                            className={`text-xs ${typeColors[entry.type] || ""}`}
                          >
                            {typeLabels[entry.type] || entry.type}
                          </Badge>
                        </TableCell>
                        <TableCell>
                          <div className="max-w-[220px]">
                            {pageTitle && (
                              <p className="text-sm font-medium truncate">
                                {pageTitle}
                              </p>
                            )}
                            <p className="text-xs text-muted-foreground font-mono truncate">
                              {displayUrl.length > 50
                                ? displayUrl.substring(0, 50) + "..."
                                : displayUrl}
                            </p>
                          </div>
                        </TableCell>
                        <TableCell>
                          {entry.isValid ? (
                            <Badge
                              variant="outline"
                              className="text-xs bg-emerald-100 text-emerald-800 border-emerald-200 dark:bg-emerald-900/30 dark:text-emerald-400 dark:border-emerald-800"
                            >
                              <CheckCircle2 className="mr-1 h-3 w-3" />
                              Geldig
                            </Badge>
                          ) : (
                            <Badge
                              variant="outline"
                              className="text-xs bg-red-100 text-red-800 border-red-200 dark:bg-red-900/30 dark:text-red-400 dark:border-red-800"
                            >
                              <XCircle className="mr-1 h-3 w-3" />
                              Ongeldig
                            </Badge>
                          )}
                        </TableCell>
                        <TableCell>
                          {entry.approvedAt ? (
                            <Badge
                              variant="outline"
                              className="text-xs bg-emerald-100 text-emerald-800 border-emerald-200 dark:bg-emerald-900/30 dark:text-emerald-400 dark:border-emerald-800"
                            >
                              Ja
                            </Badge>
                          ) : (
                            <span className="text-xs text-muted-foreground">
                              Nee
                            </span>
                          )}
                        </TableCell>
                        <TableCell className="text-sm text-muted-foreground whitespace-nowrap">
                          {new Date(entry.createdAt).toLocaleDateString("nl-NL")}
                        </TableCell>
                        <TableCell className="text-right">
                          <div
                            className="flex items-center justify-end gap-1"
                            onClick={(e) => e.stopPropagation()}
                          >
                            <Button
                              variant="ghost"
                              size="icon"
                              className="h-7 w-7"
                              onClick={() => handlePreview(entry)}
                              title="Bekijk JSON-LD"
                            >
                              <Eye className="h-3 w-3" />
                            </Button>
                            <Button
                              variant="ghost"
                              size="icon"
                              className="h-7 w-7"
                              onClick={() => handleEdit(entry)}
                              title="Bewerk JSON"
                            >
                              <Pencil className="h-3 w-3" />
                            </Button>
                            <Button
                              variant="ghost"
                              size="icon"
                              className="h-7 w-7"
                              onClick={() => handleValidate(entry)}
                              disabled={validatingId === entry.id}
                              title="Valideer"
                            >
                              {validatingId === entry.id ? (
                                <Loader2 className="h-3 w-3 animate-spin" />
                              ) : (
                                <Shield className="h-3 w-3" />
                              )}
                            </Button>
                            {!entry.approvedAt && (
                              <Button
                                variant="ghost"
                                size="icon"
                                className="h-7 w-7"
                                onClick={() => handleApprove(entry)}
                                disabled={approvingId === entry.id}
                                title="Keur goed"
                              >
                                {approvingId === entry.id ? (
                                  <Loader2 className="h-3 w-3 animate-spin" />
                                ) : (
                                  <CheckCircle2 className="h-3 w-3" />
                                )}
                              </Button>
                            )}
                            <Button
                              variant="ghost"
                              size="icon"
                              className="h-7 w-7 text-destructive hover:text-destructive"
                              onClick={() => {
                                setDeleteEntry(entry);
                                setShowDeleteDialog(true);
                              }}
                              title="Verwijder"
                            >
                              <Trash2 className="h-3 w-3" />
                            </Button>
                          </div>
                        </TableCell>
                      </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Generate Dialog */}
      <Dialog
        open={showGenerateDialog}
        onOpenChange={setShowGenerateDialog}
      >
        <DialogContent className="sm:max-w-[550px]">
          <DialogHeader>
            <DialogTitle>Gestructureerde data genereren</DialogTitle>
            <DialogDescription>
              Kies het type en de doelpagina voor je gestructureerde data
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label>Type *</Label>
              <Select
                value={generateForm.type}
                onValueChange={(val) =>
                  setGenerateForm({ ...generateForm, type: val })
                }
              >
                <SelectTrigger>
                  <SelectValue placeholder="Selecteer type" />
                </SelectTrigger>
                <SelectContent>
                  {Object.entries(typeLabels).map(([key, label]) => (
                    <SelectItem key={key} value={key}>
                      {label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label>Doelpagina</Label>
              <div className="flex items-center gap-2 mb-2">
                <Button
                  variant={!useUrlInput ? "default" : "outline"}
                  size="sm"
                  onClick={() => setUseUrlInput(false)}
                >
                  Pagina selecteren
                </Button>
                <Button
                  variant={useUrlInput ? "default" : "outline"}
                  size="sm"
                  onClick={() => setUseUrlInput(true)}
                >
                  URL invoeren
                </Button>
              </div>
              {!useUrlInput ? (
                <Select
                  value={generateForm.pageId}
                  onValueChange={(val) =>
                    setGenerateForm({ ...generateForm, pageId: val, url: "" })
                  }
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Selecteer een pagina" />
                  </SelectTrigger>
                  <SelectContent>
                    {crawledPages.length === 0 ? (
                      <SelectItem value="_none" disabled>
                        Geen pagina&apos;s gevonden
                      </SelectItem>
                    ) : (
                      crawledPages.map((page) => (
                        <SelectItem key={page.id} value={page.id}>
                          <span className="truncate max-w-[400px] block">
                            {page.title || page.url}
                          </span>
                        </SelectItem>
                      ))
                    )}
                  </SelectContent>
                </Select>
              ) : (
                <Input
                  value={generateForm.url}
                  onChange={(e) =>
                    setGenerateForm({
                      ...generateForm,
                      url: e.target.value,
                      pageId: "",
                    })
                  }
                  placeholder="https://jouwwebsite.nl/pagina"
                />
              )}
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setShowGenerateDialog(false)}
            >
              Annuleren
            </Button>
            <Button onClick={handleGenerate} disabled={isGenerating}>
              {isGenerating ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Genereren...
                </>
              ) : (
                <>
                  <Sparkles className="mr-2 h-4 w-4" />
                  Genereren
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Preview Dialog */}
      <Dialog open={showPreviewDialog} onOpenChange={setShowPreviewDialog}>
        <DialogContent className="sm:max-w-[700px]">
          <DialogHeader>
            <DialogTitle>JSON-LD preview</DialogTitle>
            <DialogDescription>
              {previewEntry && (
                <>
                  {typeLabels[previewEntry.type] || previewEntry.type} —{" "}
                  {previewEntry.url || previewEntry.page?.url || ""}
                </>
              )}
            </DialogDescription>
          </DialogHeader>
          {previewEntry && (
            <ScrollArea className="max-h-[60vh]">
              <pre className="bg-muted/50 rounded-md p-4 text-xs font-mono overflow-x-auto whitespace-pre-wrap break-words">
                {syntaxHighlight(previewEntry.data)}
              </pre>
            </ScrollArea>
          )}
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setShowPreviewDialog(false)}
            >
              Sluiten
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Edit Dialog */}
      <Dialog open={showEditDialog} onOpenChange={setShowEditDialog}>
        <DialogContent className="sm:max-w-[700px]">
          <DialogHeader>
            <DialogTitle>JSON-LD bewerken</DialogTitle>
            <DialogDescription>
              Wijzig de gestructureerde data. Zorg dat de JSON geldig is.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-2">
            <Textarea
              value={editData}
              onChange={(e) => setEditData(e.target.value)}
              className="min-h-[400px] font-mono text-xs"
            />
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setShowEditDialog(false)}
            >
              Annuleren
            </Button>
            <Button onClick={handleSaveEdit} disabled={isSaving}>
              {isSaving ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Opslaan...
                </>
              ) : (
                "Opslaan"
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Detail Dialog */}
      <Dialog open={showDetailDialog} onOpenChange={setShowDetailDialog}>
        <DialogContent className="sm:max-w-[750px]">
          {detailEntry && (
            <>
              <DialogHeader>
                <DialogTitle className="flex items-center gap-2">
                  <Badge
                    variant="outline"
                    className={`text-xs ${typeColors[detailEntry.type] || ""}`}
                  >
                    {typeLabels[detailEntry.type] || detailEntry.type}
                  </Badge>
                  Details
                </DialogTitle>
                <DialogDescription>
                  {detailEntry.url || detailEntry.page?.url || ""}
                </DialogDescription>
              </DialogHeader>

              {isLoadingDetail ? (
                <div className="flex items-center justify-center py-8">
                  <Loader2 className="h-6 w-6 animate-spin text-primary" />
                </div>
              ) : (
                <ScrollArea className="max-h-[65vh]">
                  <div className="space-y-4 pr-4">
                    <Tabs defaultValue="preview">
                      <TabsList className="w-full">
                        <TabsTrigger value="preview" className="flex-1">
                          <Code2 className="mr-1 h-3 w-3" />
                          JSON-LD
                        </TabsTrigger>
                        <TabsTrigger value="validation" className="flex-1">
                          <Shield className="mr-1 h-3 w-3" />
                          Validatie
                        </TabsTrigger>
                      </TabsList>

                      <TabsContent value="preview" className="mt-4">
                        <pre className="bg-muted/50 rounded-md p-4 text-xs font-mono overflow-x-auto whitespace-pre-wrap break-words">
                          {syntaxHighlight(detailEntry.data)}
                        </pre>
                      </TabsContent>

                      <TabsContent value="validation" className="mt-4">
                        <div className="space-y-4">
                          {/* Validity Status */}
                          <div className="flex items-center gap-2">
                            {detailEntry.isValid ? (
                              <>
                                <CheckCircle2 className="h-5 w-5 text-emerald-500" />
                                <span className="font-medium text-emerald-700 dark:text-emerald-400">
                                  Geldig
                                </span>
                              </>
                            ) : (
                              <>
                                <XCircle className="h-5 w-5 text-red-500" />
                                <span className="font-medium text-red-700 dark:text-red-400">
                                  Ongeldig
                                </span>
                              </>
                            )}
                          </div>

                          {/* Validation errors */}
                          {(() => {
                            const errors =
                              detailEntry.validation?.errors ||
                              parseJsonArray(detailEntry.validationErrors);
                            return errors.length > 0 ? (
                              <div>
                                <p className="text-sm font-medium text-red-700 dark:text-red-400 mb-2">
                                  Fouten
                                </p>
                                <div className="space-y-1">
                                  {errors.map((err, i) => (
                                    <div
                                      key={i}
                                      className="flex items-start gap-2 bg-red-50 dark:bg-red-950/20 rounded-md p-2 text-xs"
                                    >
                                      <XCircle className="h-3 w-3 text-red-500 mt-0.5 flex-shrink-0" />
                                      <span>{err}</span>
                                    </div>
                                  ))}
                                </div>
                              </div>
                            ) : null;
                          })()}

                          {/* Missing fields */}
                          {(() => {
                            const missing =
                              detailEntry.validation?.missingFields ||
                              parseJsonArray(detailEntry.missingFields);
                            return missing.length > 0 ? (
                              <div>
                                <p className="text-sm font-medium text-amber-700 dark:text-amber-400 mb-2">
                                  Ontbrekende velden
                                </p>
                                <div className="space-y-1">
                                  {missing.map((field, i) => (
                                    <div
                                      key={i}
                                      className="flex items-start gap-2 bg-amber-50 dark:bg-amber-950/20 rounded-md p-2 text-xs"
                                    >
                                      <AlertTriangle className="h-3 w-3 text-amber-500 mt-0.5 flex-shrink-0" />
                                      <span>{field}</span>
                                    </div>
                                  ))}
                                </div>
                              </div>
                            ) : null;
                          })()}

                          {/* Warnings */}
                          {detailEntry.validation?.warnings &&
                            detailEntry.validation.warnings.length > 0 && (
                              <div>
                                <p className="text-sm font-medium text-yellow-700 dark:text-yellow-400 mb-2">
                                  Waarschuwingen
                                </p>
                                <div className="space-y-1">
                                  {detailEntry.validation.warnings.map(
                                    (warn, i) => (
                                      <div
                                        key={i}
                                        className="flex items-start gap-2 bg-yellow-50 dark:bg-yellow-950/20 rounded-md p-2 text-xs"
                                      >
                                        <AlertTriangle className="h-3 w-3 text-yellow-500 mt-0.5 flex-shrink-0" />
                                        <span>{warn}</span>
                                      </div>
                                    )
                                  )}
                                </div>
                              </div>
                            )}

                          {/* No issues */}
                          {detailEntry.isValid &&
                            (!detailEntry.validation?.errors ||
                              detailEntry.validation.errors.length === 0) &&
                            (!detailEntry.validation?.missingFields ||
                              detailEntry.validation.missingFields.length ===
                                0) && (
                              <div className="flex items-center gap-2 bg-emerald-50 dark:bg-emerald-950/20 rounded-md p-3">
                                <CheckCircle2 className="h-4 w-4 text-emerald-500" />
                                <span className="text-sm text-emerald-700 dark:text-emerald-400">
                                  Geen validatieproblemen gevonden
                                </span>
                              </div>
                            )}
                        </div>
                      </TabsContent>
                    </Tabs>

                    {/* Metadata */}
                    <Separator />
                    <div className="text-xs text-muted-foreground space-y-1">
                      {detailEntry.isAutoGenerated && (
                        <p className="flex items-center gap-1">
                          <Sparkles className="h-3 w-3" />
                          Automatisch gegenereerd
                        </p>
                      )}
                      {detailEntry.approvedAt && (
                        <p>
                          Goedgekeurd:{" "}
                          {new Date(detailEntry.approvedAt).toLocaleDateString(
                            "nl-NL",
                            {
                              day: "numeric",
                              month: "short",
                              year: "numeric",
                              hour: "2-digit",
                              minute: "2-digit",
                            }
                          )}
                        </p>
                      )}
                      <p>
                        Aangemaakt:{" "}
                        {new Date(detailEntry.createdAt).toLocaleDateString(
                          "nl-NL",
                          {
                            day: "numeric",
                            month: "short",
                            year: "numeric",
                            hour: "2-digit",
                            minute: "2-digit",
                          }
                        )}
                      </p>
                    </div>
                  </div>
                </ScrollArea>
              )}

              <DialogFooter>
                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    onClick={() => handlePreview(detailEntry)}
                  >
                    <Eye className="mr-1 h-4 w-4" />
                    Preview
                  </Button>
                  <Button
                    variant="outline"
                    onClick={() => handleEdit(detailEntry)}
                  >
                    <Pencil className="mr-1 h-4 w-4" />
                    Bewerken
                  </Button>
                  {!detailEntry.approvedAt && (
                    <Button
                      onClick={() => handleApprove(detailEntry)}
                      disabled={approvingId === detailEntry.id}
                    >
                      {approvingId === detailEntry.id ? (
                        <Loader2 className="mr-1 h-4 w-4 animate-spin" />
                      ) : (
                        <CheckCircle2 className="mr-1 h-4 w-4" />
                      )}
                      Goedkeuren
                    </Button>
                  )}
                </div>
              </DialogFooter>
            </>
          )}
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <AlertDialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Verwijderen</AlertDialogTitle>
            <AlertDialogDescription>
              Weet je zeker dat je deze gestructureerde data wilt verwijderen?
              Deze actie kan niet ongedaan worden gemaakt.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Annuleren</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleDelete}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              Verwijderen
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </motion.div>
  );
}
